CREATE TABLE friends (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sendingID INT UNSIGNED NOT NULL,
    receivingID INT UNSIGNED NOT NULL,
    status TINYINT NOT NULL,  -- 1: sent, 2: accepted, 0: denied
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (sendingID) REFERENCES users(id),
    FOREIGN KEY (receivingID) REFERENCES users(id)
);
